name: Azure Pipelines
variables:
  python.version: '3.7.6'
  tfResourceGroup: 'tstate'
  tfStorageAccount: 'tstate32087'
  tfContainerName: 'tstate'
  tfWorkingDirectory: '$(Build.ArtifactStagingDirectory)/environments/test'
  connection: 'Wiggly World Connection'
  accessKey: '3+VLo8yNpOzW01P9QTe8alLGBIy9rCE2dWnGrX3566IRHYjOA9sZsegEaJqH6y5MlrhfBvxBa06N9jUznawG1Q=='
  newmanWorkingDirectory: '$(System.DefaultWorkingDirectory)/automatedtesting/postman'
  sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0Ol53Rp9MoyCRrcXwpuHbSXpvvHNT24dMy3NCnL8OD5bc2ywBMmAZAvc0BQoBZ8MxL9O67oaPENA/+C1UojdtHSyBfYXYZxRKiqFyrRTdYCqcFZ/brZfCxIeQJ7FWs5TKA2/CRMaudClnwZrrpKe8ihZyjEOyHT7AK3tHD00ixFnJ6M6WPwEEaRg0ZHMkrDKLa4+ikgg6d+cwWN80YJvpJUKgR+Qss7SD4aKI8lsXUf7KWNQgfGoppcAIdOpt95VFxUF5WzCNn8JT4a0xQdijftfeOgno2F7MITI3DLz3enk1Q4Ieo7nTxCnDM8KQUB+M0FDhQ6Tr6HQPEPKV75Cd paulw@PAUL-DESKTOP-1'
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Hosted Ubuntu 1604
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'terraform'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        ArtifactName: 'drop'
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: 'Install Terraform'
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      displayName: 'Terraform : init'
      inputs:
        backendServiceArm: '$(connection)'
        WorkingDirectory: '$(tfWorkingDirectory)'
        backendAzureRmResourceGroupName: '$(tfResourceGroup)'
        backendAzureRmStorageAccountName: '$(tfStorageAccount)'
        backendAzureRmContainerName: '$(tfContainerName)'
        backendAzureRmKey: '$(accessKey)'
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      displayName: 'Terraform : plan'
      inputs:
        command: plan
        workingDirectory: '$(tfWorkingDirectory)'
        environmentServiceNameAzureRM: '$(connection)'
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      displayName: 'Terraform : apply'
      inputs:
        command: apply
        workingDirectory: '$(tfWorkingDirectory)'
        environmentServiceNameAzureRM: '$(connection)'
    # Needed for Terraform VM deployment
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: '52.143.70.125 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBOM+qPK8T+HlsJ5+LaXMIsoiu7smcvK+lDvtoizJzu4kEd7oSWNYymvNu64ou+BaOg4dhGFWOaoXsEDQVuRwZyg='
        sshPublicKey: '$(sshPublicKey)'
        sshKeySecureFile: 'id_rsa'
    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/jmeter/fakerestapi'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
      displayName: 'Upload Package'
      artifact: drop-fakerestapi
#    - task: Bash@3
#      displayName: 'Newman: install'
#      inputs:
#        targetType: 'inline'
#        workingDirectory: '$(newmanWorkingDirectory)'
#        script: |
#          #! /bin/bash
#          sudo npm install -g newman
#    - task: Bash@3
#      displayName: 'Newman: run'
#      inputs:
#        targetType: 'inline'
#        workingDirectory: '$(newmanWorkingDirectory)'
#        script: |
#          #! /bin/bash
#          newman run Wiggly-World.postman_collection.json \
#                 -e Wiggly-World.postman_environment.json \
#                 -r "cli,json" \
#                 --reporter-json-export integration-test-results.json
#    - publish: '$(newmanWorkingDirectory)/integration-test-results.json'
#      displayName: 'Newman: publish artifacts'
#      artifact: drop-integration-test-results
- stage:
  jobs:
  - deployment: FakeRestAPI
    pool:
      vmImage: 'Ubuntu-16.04'
    environment: 'test'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: '$(connection)'
              appName: 'wiggly-api'
              appType: 'webApp'
              package: '$(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip'
  - deployment: VMDeploy
    displayName: NAME
    environment:
      name:  ENVIRONMENT NAME
      resourceType: VirtualMachine
      tags: TAG NAME
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                #! /bin/bash
              
                sudo apt-get upgrade -y
                sudo apt-get install python3-pip -y
                sudo apt-get install unzip -y
                sudo apt-get install -y chromium-browser
                pip3 install selenium
                export PATH=$PATH:some/path


