$Env:TF_VAR_subscription_id = "<subscription ID>"
$Env:TF_VAR_location = "<location>"
$Env:TF_VAR_image_resource_group = "<image resource group>"
$Env:TF_VAR_image = "<image name>"
$Env:TF_VAR_admin_username = "<vm admin account>"
$Env:TF_VAR_admin_password = "<vm admin password>"